### ISSUE TITLE
FAQ page to complete and finalise

### ISSUE THREAD

**Issue by katherinehebert** [QCBSRworkshops/QCBSRworkshops.github.io#12]
The FAQ page is (almost!) the last place that hasn't been completely filled in from the basic theme!

There are only a few questions left to answer in the FAQ (in English and in French), and the existing answers for some questions should be reviewed by different coordinators to make sure we all agree and that the answers have the correct information. 

- English FAQ: [file](https://github.com/QCBSRworkshops/QCBSRworkshops.github.io/blob/main/content/english/faq.md), [on the site](https://qcbsrworkshops.github.io/faq/)
- French FAQ: [file](https://github.com/QCBSRworkshops/QCBSRworkshops.github.io/blob/main/content/french/faq.md), [on the site](https://qcbsrworkshops.github.io/fr/faq/)

Once the FAQ are finalized, we can remove the note at the top of the page.

**Comment by pedrohbraga** [comment]
I have reviewed and added more changes to the FAQ within the latest [commits](https://github.com/QCBSRworkshops/QCBSRworkshops.github.io/commit/50073b8c08f76d127821dd10a813aa6624adf645). The latest changes still need to be translated to French.

We can do it as soon as the other coordinators review the FAQ content and add other questions they find appropriate.

**Comment by estebangongora** [comment]
I made a few minor changes on this [commit](https://github.com/QCBSRworkshops/QCBSRworkshops.github.io/commit/bfebd3b2d48b75a0824084e98a0fc4a3a8da803f). Besides those changes, it looks good to go for me!

Let me know what you think!

**Comment by katherinehebert** [comment]
New changes were translated to French in commit [7ccbfd6](https://github.com/QCBSRworkshops/QCBSRworkshops.github.io/commit/7ccbfd67d347e4b2c2b3ce9a59247ceaf29b58d7). All questions are now answered!
