### ISSUE TITLE
Contact form does not actually send us an email

### ISSUE THREAD

**Issue by katherinehebert** [QCBSRworkshops/QCBSRworkshops.github.io#13]
When you fill the contact form in "Contact", you receive a 405 Not Allowed on the message_sent page, and the email does not go through to qcbs.csbq.r@gmail.com

**Comment by antocg** [comment]
Hello,

Did it already work in the past or the contact form never worked? I looked at it a little on Google and I'm not sure if it is possible to add a contact form this way and we would probably need to pass through a provider. I think Formspree could be good, it is free up to 50 submissions (emails) per month, I don't think you ever received more emails than that number in a month? I found this video on Youtube that would be easy to follow : https://www.youtube.com/watch?v=GMyYOc8vX_E&ab_channel=JenniferSloane . What is your opinion on it?

Thank you

**Comment by katherinehebert** [comment]
Hi! We never got it to work, but also did not dig very deep to fix it. 

The Airspace theme comes with a contact page that allows people to send messages through the site without going through a separate provider. I see that we filled the parameters for the Airspace theme's contact form page in config.yaml, so there may simply be an error in the way we tried to fill this out. I am just trying something minor to see if missing quotation marks around the email address are the issue! 

Otherwise, using another provider could work, or you could remove the "send message" boxes to avoid confusion and add your own HTML link button that opens an email message window.

**Comment by katherinehebert** [comment]
Okay, that didn't work! But the commit I made will point you to the file we use to set up the parameters for the contact page, if you want to try some things with it. Otherwise, feel free to go with another solution for sure!

**Comment by antocg** [comment]
After many tests, the contact form now works well! Special thanks to ChatGPT
