### ISSUE TITLE
Update statistics on the About page with Winter 2022 data

### ISSUE THREAD

**Issue by katherinehebert** [QCBSRworkshops/QCBSRworkshops.github.io#23]
Hi guys!

The About page is not updated with stats from Winter 2022.

You can find scripts that help to update this data in QCBSRworkshops/summary-statistics, which use the payment sheets for presenters and developers to tally up unique contributors and the list of registrations to workshops. You can also update numbers manually if you know them (e.g. we updated the number of coordinators during our meeting, but only in English - this will need to be updated in the French version too!)

**Comment by katherinehebert** [comment]
Related: Update the coordinator section on this page with your own information! :) When you contribute to the website, you may also add yourselves on the readme of this website, as authors. 😄

**Comment by antocg** [comment]
Hi,

How can I find the number of registrations and participants, and just to be sure what is the difference between those two? I already found the updated number of presenters (104) and contributors (52), and I'll do the change when I'll have all the updated values.

Thanks a lot!

**Comment by katherinehebert** [comment]
Hello!

Good question! The function to see the registration list is only in the Google Drive for privacy reasons (filename: Fonction liste de participants _ Participants list function), and using this function will let you access the data from last year. This is the function that is sourced in the script [get_allparticipants](https://github.com/QCBSRworkshops/summary-statistics/blob/main/scripts/get_allparticipants.R). 

Guillaume Laroque can also help to access more of this list if needed. 

Registrations = Total number of registrations for all workshops ever.

Participants = Number of _unique_ people who have registered for at least one workshop, so we don't double count people who have registered for multiple workshops in a year.

Hope this helps!
