### ISSUE TITLE
Recommended modifications to the "Registration" page

### ISSUE THREAD

**Issue by pedrohbraga** [QCBSRworkshops/QCBSRworkshops.github.io#4]
- [x] Explicitly include the cancellation policy within this page and/or within the website. The current link brings to the wiki;
- [x] Correct "Register Now" links.

**Comment by katherinehebert** [comment]
Just to clarify: to correct the 'Register Now' links, we will put the link to the registration page on the wiki once we open registration, right?

**Comment by katherinehebert** [comment]
The registration links were corrected by @pedrohbraga in commit [5023d80](https://github.com/QCBSRworkshops/QCBSRworkshops.github.io/commit/5023d807d3022dc9730053ed0a6e40e101f4e653). Closing! 🥳
