### ISSUE TITLE
Add a detailed README description to this repository

### ISSUE THREAD

**Issue by pedrohbraga** [QCBSRworkshops/QCBSRworkshops.github.io#8]
Add a detailed README description to this repository, including a short summary, the links and snippets for the actions, the link for the website, the name of the website authors, instruction on how to contribute or report issues, copyright protections, and funding information.

**Comment by katherinehebert** [comment]
Feel free to add content to the readme I quickly assembled! I left a few sections blank, and I may be missing some relevant sections as well.
